[project]
name = "clarity-template"
requirements = []
costs_version = 1

[contracts.base]
path = "contracts/base.clar"
depends_on = []

[contracts.token]
path = "contracts/token.clar"
depends_on = ["sip-010-trait-ft-standard"]

# EXTERNAL CONTRACTS
[contracts.sip-010-trait-ft-standard]
path = "contracts/external/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.sip-009-trait-ft-standard]
path = "contracts/external/sip-009-nft-trait-standard.clar"
depends_on = []
